version: "3.8"

services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        env_file:
          - ../reviroio-junior-python-assignment/.env
        depends_on:
            - pgdb
    pgdb:
        image: pgdb-v2
        container_name: pgdb
        env_file:
          - ../reviroio-junior-python-assignment/.env
        ports:
          - 5432:5432